# Numpy

## Lists vs Numpy
- numpy is a lot faster mainly because of fixed types
- numpy has all the same functionality of lists and MORE!

## Arrays

In [21]:
import numpy as np
a = np.array([1,2,3])
b = np.array([2,3,4], dtype='int16')
a * b
c = np.array([[1,2,3], [4,5,6], [7,8,9]])

72

### Properties of Arrays

In [ ]:
b.ndim
c.ndim
a.shape
b.dtype
b.itemsize
c.size
c.nbytes

### Accessing

In [29]:
c[1, 2]
c[0, -1]
c[0, :]
c[:, 2] # interesting
c[0, 0:2]

array([1, 2])

### Modifying

In [33]:
a[2] = 10
c[:, 2] = [1,3, 5]
a

array([ 1,  2, 10])

### Initializing Different Types of Arrays

In [52]:
np.zeros((2,3), dtype='int')
np.ones((5, 4), dtype='int8')
np.full((2,2), 10, dtype='int8')

# initializing a new array with a shape similar to another array
np.full_like(c, 5)

arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=1)
r1

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

## <span style="color:skyblue">Exercise</span>
<img src="./exercise-matrix.png">

### Basic Mathematics

In [77]:
m = np.array([1,2,3])
n = np.array([2,3,4])
m + 2
m / 2
m + n
np.sin(m)

array([0.84147098, 0.90929743, 0.14112001])

### Stats

In [87]:
stats = np.array([[1,100,3], [4,5,6]])
np.min(stats)
np.min(stats, axis=0)
np.sum(stats, axis=1)

array([104,  15])

### Reorganizing Arrays

In [93]:
before = np.array([[1,2,3,4], [5,6,7,8]])
after = before.reshape((4,2))
after2 = before.reshape((2,2,2))

### Boolean Masking and Advanced Indexing

In [104]:
data = np.array([[31,5,1,6,23,1, 352], [25,6,12,754,2,5678,2345]])
data > 100
data[data > 100]


array([ 352,  754, 5678, 2345])