# Numpy

## Lists vs Numpy
- numpy is a lot faster mainly because of fixed types
- numpy has all the same functionality of lists and MORE!

## Arrays

In [41]:
import numpy as np
a = np.array([[1,2,3], [4,5,6]])
print(a.dtype)
b = np.array([2,3,4], dtype='int16')
print(a - b)


int64
[[-1 -1 -1]
 [ 2  2  2]]


### Properties of Arrays

In [45]:
# b.ndim
# c.ndim
# a.shape
# c.shape
# b.dtype
# b.itemsize

# c.size
# c.nbytes

72

### Accessing

In [55]:
c = np.array([[1,2,3], [4,5,6], [7,8,9]])
# c[2, 1]
# c[1, 2]
# c[0, -1]
# c[0, :]
# c[2]
print(c[:, 2]) # interesting

print(c[:,::2])

[3 6 9]
[[1 3]
 [4 6]
 [7 9]]


### Modifying

In [64]:
# a
# a[1] = 10
c = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(c)
c[:, 2] = [1,3, 5]
c 
# c
# a

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 2, 1],
       [4, 5, 3],
       [7, 8, 5]])

### Initializing Different Types of Arrays

In [79]:
np.zeros(2, dtype='int')
np.zeros((2,3), dtype='int')
np.ones((5, 4), dtype='int8')
np.full((2,2), 10, dtype='int8')

# # initializing a new array with a shape similar to another array
# np.full_like(c, 5)
np.full(c.shape, 5)

arr = np.array([[4,5,6]])
r1 = np.repeat(arr, 3, axis = 1)
r1

array([[4, 4, 4, 5, 5, 5, 6, 6, 6]])

## <span style="color:skyblue">Exercise</span>
<img src="./exercise-matrix.png">

In [86]:
ones = np.ones((5,5), dtype='int')
zeros = np.zeros((3,3), dtype = 'int')
zeros[1,1] = 9
zeros

ones[1:4 , 1:4] = zeros

ones

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

### Basic Mathematics

In [54]:
m = np.array([1,2,3])
n = np.array([2,3,4])
m + 2
np.sum(m)

6

### Stats

In [24]:
stats = np.array([[1,100,3], [4,5,6]])
# np.min(stats)
np.min(stats, axis=0)
# np.sum(stats, axis=1)

array([1, 5, 3])

### Reorganizing Arrays

In [93]:
before = np.array([[1,2,3,4], [5,6,7,8]])
after = before.reshape((4,2))
after2 = before.reshape((2,2,2))

### Boolean Masking and Advanced Indexing

In [104]:
data = np.array([[31,5,1,6,23,1, 352], [25,6,12,754,2,5678,2345]])
data > 100
data[data > 100]


array([ 352,  754, 5678, 2345])